/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author usu21
 */
public class GestionProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form GestionProductos
     */
    public GestionProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Me aseguro que hayan seleccionado un cliente
        if(jTable1.getSelectedRowCount() == 0){ //Si la fila seleccionada es 0 (no seleccionado)
            JOptionPane.showMessageDialog(this, "Debes seleccionar un cliente",
                " Cliente no seleccionado", JOptionPane.ERROR_MESSAGE);
        } else{
            //Creamos una copia del clienteSeleccionado por si finalmente cancelan
            //Vamos al Cliente.java
            Cliente copia = (Cliente) clienteSeleccionado.clone();
            DatosCliente dc = new DatosCliente(null, true, clienteSeleccionado, "Modificar");
            dc.setLocationRelativeTo(null);
            dc.setVisible(true);
            //si se ha pulsado cancelar restauro los datos de la copia en el clienteSeleccionado
            if(dc.cancelar){
                clienteSeleccionado.setNif(copia.getNif());
                clienteSeleccionado.setNombre(copia.getNombre());
                clienteSeleccionado.setApellidos(copia.getApellidos());
                clienteSeleccionado.setDireccion(copia.getDireccion());
                clienteSeleccionado.setPoblacion(copia.getPoblacion());

            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Nos aseguramos que hayan seleccionado algun cliente
        if(jTable1.getSelectedRowCount() == 0){ //Si la fila seleccionada es 0 (no seleccionado)
            JOptionPane.showMessageDialog(this, "Debes seleccionar un cliente",
                " Cliente no seleccionado", JOptionPane.ERROR_MESSAGE);
        } else{
            //Le pedimos confirmacion para borrar
            int respuesta = JOptionPane.showConfirmDialog(this, "¿Estas seguro que quieres borrar el cliente seleccionado?",
                "Confirmación", JOptionPane.YES_NO_OPTION);
            if(respuesta == JOptionPane.YES_OPTION){
                //Si ha respondido que si eliminamos el cliente y grabamos
                todosLosClientes.bajaCliente(clienteSeleccionado);
                SupermercadoMar.ficheroClientes.grabar(clientes);
                JOptionPane.showMessageDialog(this, "Cliente borrado!");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
